catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - cached-factory@0.1.0
  - ts-api-utils@2.2.0
  - undici-types@6.21.0

catalog:
  '@schplitt/eslint-config': ^1.3.0
  bumpp: ^10.4.1
  changelogithub: ^14.0.0
  eslint: ^9.39.2
  tsdown: ^0.20.3
  typescript: ^5.9.3
  vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
